"""
Builds the .pptx presentation for:
"Process-Aware Authenticity Detection in Supervised Programming Labs"
using the flowchart PNGs generated by flowcharts/generate_flowcharts.py.

Run: python3 generate_presentation.py
"""

import os
from pptx import Presentation
from pptx.util import Inches, Pt, Emu
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN, MSO_ANCHOR
from pptx.enum.shapes import MSO_SHAPE
from pptx.oxml.ns import qn

HERE = os.path.dirname(os.path.abspath(__file__))
IMG = os.path.join(HERE, "flowcharts")

NAVY = RGBColor(0x1B, 0x2A, 0x4A)
BLUE = RGBColor(0x2E, 0x5A, 0xAC)
TEAL = RGBColor(0x1B, 0x8A, 0x8A)
AMBER = RGBColor(0xC9, 0x72, 0x0B)
RED = RGBColor(0xB2, 0x3A, 0x48)
GREY = RGBColor(0x5A, 0x64, 0x72)
LIGHT_BG = RGBColor(0xF7, 0xF8, 0xFA)
WHITE = RGBColor(0xFF, 0xFF, 0xFF)

SLIDE_W = Inches(13.333)
SLIDE_H = Inches(7.5)

prs = Presentation()
prs.slide_width = SLIDE_W
prs.slide_height = SLIDE_H
BLANK = prs.slide_layouts[6]


def add_slide():
    return prs.slides.add_slide(BLANK)


def set_bg(slide, color=WHITE):
    bg = slide.background
    bg.fill.solid()
    bg.fill.fore_color.rgb = color


def add_rect(slide, x, y, w, h, color, line_color=None):
    shp = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, x, y, w, h)
    shp.fill.solid()
    shp.fill.fore_color.rgb = color
    if line_color is None:
        shp.line.fill.background()
    else:
        shp.line.color.rgb = line_color
        shp.line.width = Pt(0.75)
    shp.shadow.inherit = False
    return shp


def add_text(slide, x, y, w, h, text, size=18, color=NAVY, bold=False,
             align=PP_ALIGN.LEFT, italic=False, font="Calibri", anchor=MSO_ANCHOR.TOP,
             line_spacing=1.0):
    tb = slide.shapes.add_textbox(x, y, w, h)
    tf = tb.text_frame
    tf.word_wrap = True
    tf.vertical_anchor = anchor
    lines = text.split("\n")
    for i, line in enumerate(lines):
        p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
        p.text = line
        p.alignment = align
        p.line_spacing = line_spacing
        for run in p.runs:
            run.font.size = Pt(size)
            run.font.bold = bold
            run.font.italic = italic
            run.font.color.rgb = color
            run.font.name = font
    return tb


def add_bullets(slide, x, y, w, h, items, size=16, color=GREY, bold_first=False,
                 font="Calibri", space_after=8, bullet_color=None, line_spacing=1.08):
    tb = slide.shapes.add_textbox(x, y, w, h)
    tf = tb.text_frame
    tf.word_wrap = True
    for i, item in enumerate(items):
        p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
        if isinstance(item, tuple):
            level, txt = item
        else:
            level, txt = 0, item
        p.text = ("•  " if level == 0 else "‒  ") + txt
        p.level = 0
        p.space_after = Pt(space_after)
        p.line_spacing = line_spacing
        for run in p.runs:
            run.font.size = Pt(size - (2 if level else 0))
            run.font.color.rgb = color
            run.font.name = font
    return tb


def add_pagenum(slide, n):
    add_text(slide, Inches(12.55), Inches(7.12), Inches(0.6), Inches(0.3),
              str(n), size=11, color=GREY, align=PP_ALIGN.RIGHT)


def add_kicker(slide, text):
    add_rect(slide, 0, 0, Inches(0.18), SLIDE_H, NAVY)
    add_text(slide, Inches(0.5), Inches(0.28), Inches(9), Inches(0.4),
              text.upper(), size=13, color=AMBER, bold=True, font="Calibri")


def title_slide():
    s = add_slide()
    set_bg(s, NAVY)
    add_rect(s, 0, Inches(6.55), SLIDE_W, Inches(0.08), AMBER)
    add_text(s, Inches(0.9), Inches(2.35), Inches(11.5), Inches(1.9),
              "Process-Aware Authenticity Detection\nin Supervised Programming Labs",
              size=38, color=WHITE, bold=True, align=PP_ALIGN.LEFT, line_spacing=1.05)
    add_text(s, Inches(0.9), Inches(4.15), Inches(11), Inches(0.6),
              "Catching live, in-person proxy-typing that no current attendance\nor plagiarism system is built to detect",
              size=18, color=RGBColor(0xC9, 0xD6, 0xEE), align=PP_ALIGN.LEFT, line_spacing=1.2)
    add_text(s, Inches(0.9), Inches(6.7), Inches(8), Inches(0.5),
              "M.Tech Research Proposal  ·  CodeHamsters, M.Tech CSE  ·  IIIT Surat",
              size=14, color=RGBColor(0x9D, 0xAE, 0xD1))
    return s


def section_header(slide_no, kicker, title, subtitle=None):
    s = add_slide()
    set_bg(s)
    add_kicker(s, kicker)
    add_text(s, Inches(0.5), Inches(0.62), Inches(12.3), Inches(0.9),
              title, size=30, color=NAVY, bold=True)
    if subtitle:
        add_text(s, Inches(0.5), Inches(1.28), Inches(12.3), Inches(0.5),
                  subtitle, size=15, color=GREY, italic=True)
    add_pagenum(s, slide_no)
    return s


def add_image_centered(slide, path, top, max_w, max_h, left=None):
    from PIL import Image
    with Image.open(path) as im:
        pw, ph = im.size
    ratio = pw / ph
    w = max_w
    h = w / ratio
    if h > max_h:
        h = max_h
        w = h * ratio
    if left is None:
        left = (SLIDE_W - w) / 2
    slide.shapes.add_picture(path, left, top, width=w, height=h)
    return left, top, w, h


# ---------------------------------------------------------------- Slide 1
title_slide()

# ---------------------------------------------------------------- Slide 2: The Problem
s = section_header(2, "The Problem", "Labs Verify Presence, Not Authorship")
add_text(s, Inches(0.5), Inches(1.75), Inches(12.3), Inches(0.8),
          "A friend can sit in for 45 minutes and type live at a classmate's terminal, in full view\n"
          "of an instructor — and no current system is built to catch it.",
          size=17, color=GREY, line_spacing=1.25)

tbl_top = Inches(2.85)
add_rect(s, Inches(0.9), tbl_top, Inches(5.4), Inches(1.7), RGBColor(0xE7, 0xF6, 0xEC), line_color=RGBColor(0x2F, 0x9E, 0x5B))
add_text(s, Inches(1.15), tbl_top + Inches(0.15), Inches(5.0), Inches(0.5),
          "✅ Verified today", size=17, bold=True, color=RGBColor(0x1E, 0x6B, 0x3D))
add_text(s, Inches(1.15), tbl_top + Inches(0.65), Inches(5.0), Inches(0.95),
          "Physical identity & presence\nID card · biometric · face match · RFID",
          size=14.5, color=GREY, line_spacing=1.2)

add_rect(s, Inches(6.9), tbl_top, Inches(5.4), Inches(1.7), RGBColor(0xF9, 0xE4, 0xE6), line_color=RED)
add_text(s, Inches(7.15), tbl_top + Inches(0.15), Inches(5.0), Inches(0.5),
          "❌ Not verified", size=17, bold=True, color=RED)
add_text(s, Inches(7.15), tbl_top + Inches(0.65), Inches(5.0), Inches(0.95),
          "Authorship of the code being typed, live,\nin that same session",
          size=14.5, color=GREY, line_spacing=1.2)

add_text(s, Inches(0.9), Inches(5.05), Inches(11.4), Inches(1.6),
          "This proposal asks a narrow, previously unasked question: once a student is physically\n"
          "present and identity-verified, is anyone checking that the hands on the keyboard are theirs?",
          size=16.5, color=NAVY, italic=True, line_spacing=1.3)

# ---------------------------------------------------------------- Slide 3: Literature landscape
s = section_header(3, "Literature Landscape", "Two Active Research Threads")
items_left = [
    "Targets: take-home, asynchronous cheating",
    "Signal: keystroke timing, edit sequences",
    "Adversary: a student alone, unlimited time,\ndisguising an LLM answer",
    "Key work: Nosi IDE (2026) · keystroke-dishonesty\npapers (2025) · Crossley et al. (2024) · CodeBench",
]
items_right = [
    "Targets: impersonation at check-in",
    "Signal: face match, RFID, weight sensors, biometrics",
    "Adversary: someone else physically checks in\non your behalf",
    "Key work: Ege & Özdemir (2026, RFID+weight) ·\nfacial-recognition CCTV · NFC/biometric check-in",
]
add_rect(s, Inches(0.6), Inches(1.7), Inches(5.9), Inches(0.65), BLUE)
add_text(s, Inches(0.75), Inches(1.78), Inches(5.6), Inches(0.5),
          "Thread 1 — Process-Driven Authenticity Detection", size=15, bold=True, color=WHITE)
add_bullets(s, Inches(0.75), Inches(2.55), Inches(5.6), Inches(3.5), items_left, size=14.5)

add_rect(s, Inches(6.85), Inches(1.7), Inches(5.9), Inches(0.65), TEAL)
add_text(s, Inches(7.0), Inches(1.78), Inches(5.6), Inches(0.5),
          "Thread 2 — Physical Proxy Attendance Detection", size=15, bold=True, color=WHITE)
add_bullets(s, Inches(7.0), Inches(2.55), Inches(5.6), Inches(3.5), items_right, size=14.5)

add_text(s, Inches(0.6), Inches(6.55), Inches(12.1), Inches(0.6),
          "Neither literature covers a student who is physically present and identity-verified, "
          "while someone else does the actual coding live, under supervision.",
          size=13.5, color=AMBER, bold=True, italic=True)

# ---------------------------------------------------------------- Slide 4: The Gap (flowchart)
s = section_header(4, "Research Gap", "The Unaddressed Intersection")
add_image_centered(s, os.path.join(IMG, "01_research_gap.png"), Inches(1.55), Inches(11.6), Inches(5.6))
add_pagenum(s, 4)

# ---------------------------------------------------------------- Slide 5: Confirmed vs open
s = section_header(5, "Literature Survey", "What's Confirmed, What's Still Open")
rows = [
    ("CodeBench collected fine-grained data from 2,058 students,\n16 CS1 courses", "✅ Confirmed", RGBColor(0x1E,0x6B,0x3D)),
    ("Sequential/clustering analysis of programming trajectories\npredicts learning outcomes", "✅ Confirmed", RGBColor(0x1E,0x6B,0x3D)),
    ("AST-evolution / structural-jump detection for pasted code\nas a live, single-session anomaly signal", "⚠️ Open application", AMBER),
    ("Proxy-attendance research uses IDE process data", "❌ Not found — confirms the gap", RED),
]
y = Inches(1.85)
for claim, status, color in rows:
    add_rect(s, Inches(0.6), y, Inches(12.1), Inches(1.05), LIGHT_BG, line_color=RGBColor(0xDD,0xE1,0xE7))
    add_text(s, Inches(0.85), y + Inches(0.12), Inches(8.3), Inches(0.85), claim, size=14, color=NAVY, line_spacing=1.15)
    add_text(s, Inches(9.25), y + Inches(0.28), Inches(3.3), Inches(0.5), status, size=13.5, bold=True, color=color)
    y += Inches(1.2)

# ---------------------------------------------------------------- Slide 6: Comparative analysis
s = section_header(6, "Comparative Analysis", "Where the Proposed Study Sits")
headers = ["Dimension", "Process-Driven Work\n(Nosi IDE, keystroke papers)", "Attendance Systems\n(RFID / biometric)", "Proposed Study"]
data = [
    ["Adversary model", "Solo student, at home,\nunlimited time", "Someone else checks\nin for you", "Someone else types for\nyou, live, in the room"],
    ["Setting", "Take-home / asynchronous", "Entry checkpoint only", "Supervised, in-session lab"],
    ["Signal", "Keystroke IAT,\nedit sequences", "Face / RFID / weight", "Keystroke IAT + edit\nsequence + AST jumps"],
    ["Ground truth", "N=5 proof-of-concept\n(Nosi)", "Sensor accuracy\nbenchmarks", "Controlled in-lab groups:\ngenuine/proxy/minimal"],
]
col_x = [Inches(0.5), Inches(2.85), Inches(6.35), Inches(9.85)]
col_w = [Inches(2.3), Inches(3.4), Inches(3.4), Inches(2.95)]
y0 = Inches(1.7)
row_h = Inches(0.62)
for c, (x, w, htext) in enumerate(zip(col_x, col_w, headers)):
    fill = NAVY if c < 3 else AMBER
    add_rect(s, x, y0, w, row_h, fill)
    add_text(s, x + Inches(0.08), y0 + Inches(0.06), w - Inches(0.16), row_h - Inches(0.1),
              htext, size=11.5, bold=True, color=WHITE, line_spacing=1.0)
y = y0 + row_h
for r, row in enumerate(data):
    band = LIGHT_BG if r % 2 == 0 else WHITE
    for c, (x, w, val) in enumerate(zip(col_x, col_w, row)):
        fill = RGBColor(0xFC, 0xEF, 0xDA) if c == 3 else band
        add_rect(s, x, y, w, Inches(1.05), fill, line_color=RGBColor(0xE2,0xE5,0xEA))
        add_text(s, x + Inches(0.08), y + Inches(0.06), w - Inches(0.16), Inches(0.95),
                  val, size=11.5, bold=(c == 0), color=NAVY if c!=3 else RGBColor(0x7A,0x3E,0x00), line_spacing=1.05)
    y += Inches(1.05)

# ---------------------------------------------------------------- Slide 7: Research Question
s = section_header(7, "The Question", "Research Question")
add_rect(s, Inches(1.0), Inches(2.0), Inches(11.3), Inches(2.6), NAVY)
add_text(s, Inches(1.4), Inches(2.35), Inches(10.5), Inches(2.0),
          "Can IDE-level process signals — keystroke timing, edit/execution\n"
          "sequences, and structural code jumps — distinguish a student's own\n"
          "authentic in-lab work from proxy-typed or minimally-engaged work, and\n"
          "do they generalize better or worse than the equivalent signals already\n"
          "shown to detect take-home LLM-scribing?",
          size=18, color=WHITE, bold=True, align=PP_ALIGN.CENTER, line_spacing=1.3,
          anchor=MSO_ANCHOR.MIDDLE)
add_text(s, Inches(1.0), Inches(4.95), Inches(11.3), Inches(1.3),
          "This positions the thesis directly against Lueder et al. (2026, Nosi IDE) and the 2024–25 "
          "keystroke-dishonesty line of work — extending them into an untested adversary setting "
          "rather than re-deriving their framing. Either outcome (the signals transfer, or they don't) "
          "is a publishable result.",
          size=15, color=GREY, italic=True, align=PP_ALIGN.CENTER, line_spacing=1.3)

# ---------------------------------------------------------------- Slide 8: System architecture (flowchart)
s = section_header(8, "Proposed Methodology", "System: A Process-Instrumented Lab IDE")
add_image_centered(s, os.path.join(IMG, "02_system_architecture.png"), Inches(1.9), Inches(12.2), Inches(4.6))
add_text(s, Inches(0.6), Inches(6.65), Inches(12.1), Inches(0.6),
          "Key design choice: unlike Nosi IDE (encrypted, take-home, N=5), this system runs on lab "
          "workstations already under instructor supervision.",
          size=13, color=GREY, italic=True)

# ---------------------------------------------------------------- Slide 9: Study design (flowchart)
s = section_header(9, "Proposed Methodology", "Controlled Ground-Truth Study Design")
add_image_centered(s, os.path.join(IMG, "03_study_design.png"), Inches(1.55), Inches(9.6), Inches(5.65))

# ---------------------------------------------------------------- Slide 10: Ethics & Scope
s = section_header(10, "Methodology", "Ethics & Scope Discipline")
add_rect(s, Inches(0.6), Inches(1.75), Inches(5.9), Inches(4.6), LIGHT_BG, line_color=RGBColor(0xDD,0xE1,0xE7))
add_text(s, Inches(0.85), Inches(1.95), Inches(5.4), Inches(0.5), "Ethics Note", size=17, bold=True, color=RED)
add_bullets(s, Inches(0.85), Inches(2.55), Inches(5.4), Inches(3.6), [
    "Keystroke logs can act as a biometric identifier",
    "Requires a de-identification plan before any deployment",
    "IRB / ethics approval required before deployment",
    "Any published dataset needs the same safeguards\ndiscussed in prior keystroke-data surveys",
], size=14.5)

add_rect(s, Inches(6.85), Inches(1.75), Inches(5.9), Inches(4.6), LIGHT_BG, line_color=RGBColor(0xDD,0xE1,0xE7))
add_text(s, Inches(7.1), Inches(1.95), Inches(5.4), Inches(0.5), "Scope Discipline", size=17, bold=True, color=BLUE)
add_bullets(s, Inches(7.1), Inches(2.55), Inches(5.4), Inches(3.6), [
    "Original pitch suggested 5 parallel research models across\n100–300 students for 8–12 weeks — multiple papers' worth",
    "This thesis scopes to ONE defensible contribution:\nthe controlled authenticity-classification study",
    "Engagement modeling & learning-outcome prediction are\nlabeled future work, not promised deliverables",
], size=14.5)

# ---------------------------------------------------------------- Slide 11: Roadmap (flowchart)
s = section_header(11, "Putting It Together", "Research Roadmap")
add_image_centered(s, os.path.join(IMG, "04_research_roadmap.png"), Inches(1.55), Inches(6.6), Inches(5.65))

# ---------------------------------------------------------------- Slide 12: Expected Contributions
s = section_header(12, "Contributions", "Expected Contributions")
contribs = [
    "First controlled comparison of take-home authenticity signals (keystroke IAT) against a live, in-person proxy-typing adversary",
    "A ground-truth methodology using in-lab controlled groups instead of small asynchronous proof-of-concept studies",
    "An empirical answer to whether existing keystroke/process features transfer across adversary settings — a positive or a null result both add value",
    "A scoped, deployable instructor-facing flagging tool for supervised programming labs specifically (distinct from Nosi's take-home use case)",
]
y = Inches(1.9)
for i, c in enumerate(contribs, start=1):
    add_rect(s, Inches(0.6), y, Inches(0.7), Inches(1.05), AMBER)
    add_text(s, Inches(0.6), y, Inches(0.7), Inches(1.05), str(i), size=26, bold=True, color=WHITE,
              align=PP_ALIGN.CENTER, anchor=MSO_ANCHOR.MIDDLE)
    add_rect(s, Inches(1.4), y, Inches(11.3), Inches(1.05), LIGHT_BG, line_color=RGBColor(0xDD,0xE1,0xE7))
    add_text(s, Inches(1.65), y + Inches(0.08), Inches(10.8), Inches(0.9), c, size=14.5, color=NAVY,
              anchor=MSO_ANCHOR.MIDDLE, line_spacing=1.15)
    y += Inches(1.2)

# ---------------------------------------------------------------- Slide 13: Closing / Thank you
s = add_slide()
set_bg(s, NAVY)
add_rect(s, 0, Inches(6.55), SLIDE_W, Inches(0.08), AMBER)
add_text(s, Inches(0.9), Inches(2.8), Inches(11.5), Inches(1.2),
          "Thank You", size=40, color=WHITE, bold=True)
add_text(s, Inches(0.9), Inches(3.85), Inches(11), Inches(0.6),
          "Questions & Discussion", size=18, color=RGBColor(0xC9, 0xD6, 0xEE))
add_text(s, Inches(0.9), Inches(6.7), Inches(8), Inches(0.5),
          "CodeHamsters, M.Tech CSE  ·  IIIT Surat", size=13, color=RGBColor(0x9D, 0xAE, 0xD1))

out_path = os.path.join(HERE, "Process-Aware_Authenticity_Detection_Presentation.pptx")
prs.save(out_path)
print("Saved:", out_path)
